//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISI.VisualStudio.Extensions.RecipeExtensions {
    using System;
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AspNetWebApi_5x_Recipes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AspNetWebApi_5x_Recipes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ISI.VisualStudio.Extensions.RecipeExtensions.AspNetWebApi_5x_Recipes", typeof(AspNetWebApi_5x_Recipes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${Usings}
        ///
        ///namespace ${Namespace.Area}.Controllers
        ///{
        ///	public partial class ${ControllerKey}Controller 
        ///	{
        ///		[System.Web.Http.AcceptVerbs(System.Net.WebRequestMethods.Http.Get)]
        ///		public virtual System.Net.Http.HttpResponseMessage ${ControllerActionKey}()
        ///		{
        ///			System.Net.Http.HttpResponseMessage result = null;
        ///
        ///			var model = new ${Namespace.Area}.Models.${ControllerKey}.${ControllerActionKey}Model();
        ///
        ///			result = Request.CreateViewResponse(${Namespace}.T4Files.${Areas.AreaName}Views.${Control [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddActionWithPartialView_Action {
            get {
                return ResourceManager.GetString("AddActionWithPartialView_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace ${Namespace.Area}.Models.${ControllerKey}
        ///{
        ///	public class ${ControllerActionKey}Model : BaseModel
        ///	{
        ///
        ///	}
        ///}.
        /// </summary>
        internal static string AddActionWithPartialView_Model {
            get {
                return ResourceManager.GetString("AddActionWithPartialView_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @inherits ISI.Libraries.RazorEngine.WebApi.TemplateBase&lt;${Namespace.Area}.Models.${ControllerKey}.${ControllerActionKey}Model&gt;.
        /// </summary>
        internal static string AddActionWithPartialView_PartialView {
            get {
                return ResourceManager.GetString("AddActionWithPartialView_PartialView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${Usings}
        ///
        ///namespace ${Namespace.Area}.Controllers
        ///{
        ///	public partial class ${ControllerKey}Controller 
        ///	{
        ///		[System.Web.Http.AcceptVerbs(System.Net.WebRequestMethods.Http.Get)]
        ///		public virtual System.Net.Http.HttpResponseMessage ${ControllerActionKey}()
        ///		{
        ///			System.Net.Http.HttpResponseMessage result = null;
        ///
        ///			var model = new ${Namespace.Area}.Models.${ControllerKey}.${ControllerActionKey}Model();
        ///
        ///			result = Request.CreateViewResponse(${Namespace}.T4Files.${Areas.AreaName}Views.${Control [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddActionWithView_Action {
            get {
                return ResourceManager.GetString("AddActionWithView_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jQuery.namespace(&quot;${Namespace.Area}.${ControllerKey}.${ControllerActionKey}&quot;, function(jQuery) {
        ///	var model = {};
        ///	var view = {};
        ///	var controller = {
        ///		setup: function (config) {
        ///			controller.eventBinder();
        ///		},
        ///		eventBinder: function () {
        ///		}
        ///	};
        ///
        ///	return {
        ///		Setup: controller.setup
        ///	};
        ///} (jQuery));
        ///
        ///jQuery(document).ready(function (jQuery) {
        ///	${Namespace.Area}.${ControllerKey}.${ControllerActionKey}.Setup();
        ///});.
        /// </summary>
        internal static string AddActionWithView_JavaScript {
            get {
                return ResourceManager.GetString("AddActionWithView_JavaScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace ${Namespace.Area}.Models.${ControllerKey}
        ///{
        ///	public class ${ControllerActionKey}Model : BaseModel
        ///	{
        ///
        ///	}
        ///}.
        /// </summary>
        internal static string AddActionWithView_Model {
            get {
                return ResourceManager.GetString("AddActionWithView_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Html.ImportStyleSheet(${Namespace}.T4Links.StyleSheets._Shared._Definitions_csless).
        /// </summary>
        internal static string AddActionWithView_StyleSheet {
            get {
                return ResourceManager.GetString("AddActionWithView_StyleSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @inherits ISI.Libraries.RazorEngine.WebApi.TemplateBase&lt;${Namespace.Area}.Models.${ControllerKey}.${ControllerActionKey}Model&gt;
        ///
        ///@{
        ///	Model.SetTitle(&quot;${ViewTitle}&quot;);
        ///	Layout = ${Namespace}.T4Files.${Areas.AreaName}Views.${ControllerKey}._Layout_cshtml;
        ///}
        ///
        ///@section StyleSheetIncludes
        ///{
        ///	@Html.AddStyleSheet(${Namespace}.T4Links.${Areas.AreaName}StyleSheets.${ControllerKey}.${ControllerActionKey}_csless)
        ///}
        ///
        ///@section JavaScriptIncludes
        ///{
        ///	@Html.AddJavaScript(${Namespace}.T4Links.${Areas.AreaName}Jav [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddActionWithView_View {
            get {
                return ResourceManager.GetString("AddActionWithView_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace ${Namespace}.Models
        ///{
        ///	public abstract class BaseModel
        ///	{
        ///
        ///	}
        ///}.
        /// </summary>
        internal static string AddArea_BaseModelRoot {
            get {
                return ResourceManager.GetString("AddArea_BaseModelRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Net;
        ///using System.Net.Http;
        ///using System.Web.Http;
        ///using ISI.Libraries.Extensions;
        ///
        ///namespace ${Namespace.Area}.Controllers
        ///{
        ///	public abstract partial class Controller : ISI.Libraries.WebApi.AbstractController
        ///	{
        ///		protected Controller(ISI.Libraries.Tracing.ITrace trace)
        ///			: base(trace)
        ///		{
        ///
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string AddArea_ControllerRoot {
            get {
                return ResourceManager.GetString("AddArea_ControllerRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace ${Namespace.Area}.Models.${ControllerKey}
        ///{
        ///	public abstract class BaseModel : Models.BaseModel
        ///	{
        ///	}
        ///}.
        /// </summary>
        internal static string AddController_BaseModel {
            get {
                return ResourceManager.GetString("AddController_BaseModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace ${Namespace}.Models
        ///{
        ///	public abstract class BaseModel
        ///	{
        ///
        ///	}
        ///}.
        /// </summary>
        internal static string AddController_BaseModelRoot {
            get {
                return ResourceManager.GetString("AddController_BaseModelRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Net;
        ///using System.Net.Http;
        ///using System.Web.Http;
        ///using ISI.Libraries.Extensions;
        ///
        ///namespace ${Namespace.Area}.Controllers
        ///{
        ///	public partial class ${ControllerKey}Controller : ApiController
        ///	{
        ///		public ${ControllerKey}Controller(ISI.Libraries.Tracing.ITrace trace)
        ///			: base(trace)
        ///		{
        ///
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string AddController_Controller {
            get {
                return ResourceManager.GetString("AddController_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Net;
        ///using System.Net.Http;
        ///using System.Web.Http;
        ///using ISI.Libraries.Extensions;
        ///
        ///namespace ${Namespace.Area}.Controllers
        ///{
        ///	public abstract partial class Controller : ISI.Libraries.WebApi.AbstractController
        ///	{
        ///		protected Controller(ISI.Libraries.Tracing.ITrace trace)
        ///			: base(trace)
        ///		{
        ///
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string AddController_ControllerRoot {
            get {
                return ResourceManager.GetString("AddController_ControllerRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Threading.Tasks;
        ///using ISI.Libraries.Web.Routes;
        ///
        ///namespace ${Namespace.Area}
        ///{
        ///	public partial class Routes
        ///	{
        ///		public partial class ${ControllerKey}
        ///		{
        ///			#pragma warning disable 649
        ///			public class RouteNames : IRouteNames
        ///			{
        ///				//${RouteNames}
        ///			}
        ///			#pragma warning restore 649
        ///
        ///			static ${ControllerKey}()
        ///			{
        ///				(new RouteNames()).AssignRouteNa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddController_Routes {
            get {
                return ResourceManager.GetString("AddController_Routes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Threading.Tasks;
        ///
        ///namespace ${Namespace.Area}
        ///{
        ///	public partial class Routes
        ///	{
        ///		internal static readonly string UrlRoot = string.Empty;
        ///
        ///		public static void RegisterRoutes(System.Web.Http.HttpRouteCollection routes)
        ///		{
        ///			//${ApiRoutes}
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string AddController_RoutesRoot {
            get {
                return ResourceManager.GetString("AddController_RoutesRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Net;
        ///using System.Net.Http;
        ///using System.Web.Http;
        ///using ISI.Libraries.WebApi.Extensions;
        ///using ISI.Libraries.Extensions;
        ///
        ///namespace ${Namespace.Area}.Controllers
        ///{
        ///	public partial class ${ControllerKey}Controller 
        ///	{
        ///		[AcceptVerbs(WebRequestMethods.Http.Get)]
        ///		public virtual HttpResponseMessage ${ControllerActionKey}()
        ///		{
        ///			HttpResponseMessage result = null; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddRestMethod_Method {
            get {
                return ResourceManager.GetString("AddRestMethod_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using ISI.Libraries.Extensions;
        ///
        ///namespace ${Namespace.Area}.Models.${ControllerKey}
        ///{
        ///	public class ${ControllerActionKey}Model : BaseModel
        ///	{
        ///
        ///	}
        ///}.
        /// </summary>
        internal static string AddRestMethod_Model {
            get {
                return ResourceManager.GetString("AddRestMethod_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jQuery.namespace(&quot;${Namespace.Area}.${ControllerKey}.Layout&quot;, function(jQuery) {
        ///	var model = {};
        ///	var view = {};
        ///	var controller = {
        ///		setup: function (config) {
        ///			controller.eventBinder();
        ///		},
        ///		eventBinder: function () {
        ///		}
        ///	};
        ///
        ///	return {
        ///		Setup: controller.setup
        ///	};
        ///} (jQuery));
        ///
        ///jQuery(document).ready(function (jQuery) {
        ///	${Namespace.Area}.${ControllerKey}.Layout.Setup();
        ///});.
        /// </summary>
        internal static string JavaScriptsControllerLayout {
            get {
                return ResourceManager.GetString("JavaScriptsControllerLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Html.ImportStyleSheet(${Namespace}.T4Links.StyleSheets._Shared._Definitions_csless).
        /// </summary>
        internal static string StyleSheetsControllerLayout {
            get {
                return ResourceManager.GetString("StyleSheetsControllerLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model ${Namespace.Area}.Models.${ControllerKey}.BaseModel
        ///
        ///@{
        ///	Layout = ${Namespace}.T4Files.${Areas.AreaName}Views._Shared._Layout_cshtml;
        ///}
        ///
        ///@section StyleSheetIncludes
        ///{
        ///	@Html.AddStyleSheet(${Namespace}.T4Links.${Areas.AreaName}StyleSheets.${ControllerKey}._Layout_csless)
        ///	@RenderSection(&quot;StyleSheetIncludes&quot;, false)
        ///}
        ///
        ///@RenderBody()
        ///
        ///@section JavaScriptIncludes
        ///{
        ///	@Html.AddJavaScript(${Namespace}.T4Links.${Areas.AreaName}JavaScripts.${ControllerKey}._Layout_csjs)
        ///	@RenderSection(&quot;JavaS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ViewsControllerLayout {
            get {
                return ResourceManager.GetString("ViewsControllerLayout", resourceCulture);
            }
        }
    }
}
