//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISI.VisualStudio.Extensions.RecipeExtensions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AspNetMvc_5x_Recipes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AspNetMvc_5x_Recipes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ISI.VisualStudio.Extensions.RecipeExtensions.AspNetMvc_5x_Recipes", typeof(AspNetMvc_5x_Recipes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${Usings}
        ///
        ///namespace ${Namespace.Area}.Controllers
        ///{
        ///	public partial class ${ControllerKey}Controller 
        ///	{
        ///		[AcceptVerbs(HttpVerbs.Post)]
        ///		public virtual ActionResult ${ControllerActionKey}()
        ///		{
        ///			ActionResult result = null;
        ///
        ///			var model = new ${Namespace.Area}.Models.${ControllerKey}.${ControllerActionKey}Model();
        ///
        ///			result = PartialView(${Namespace}.T4Files.${Areas.AreaName}Views.${ControllerKey}.Partials.${ControllerActionKey}_cshtml, model);
        ///
        ///			return result;
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string AddActionWithPartialView_Action {
            get {
                return ResourceManager.GetString("AddActionWithPartialView_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Web;
        ///using System.Web.Mvc;
        ///using ISI.Libraries.Web.Mvc.Extensions;
        ///using ISI.Libraries.Extensions;
        ///
        ///
        ///namespace ${Namespace.Area}.Models.${ControllerKey}
        ///{
        ///	public class ${ControllerActionKey}Model : BaseModel
        ///	{
        ///
        ///	}
        ///}.
        /// </summary>
        internal static string AddActionWithPartialView_Model {
            get {
                return ResourceManager.GetString("AddActionWithPartialView_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model ${Namespace.Area}.Models.${ControllerKey}.${ControllerActionKey}Model
        ///.
        /// </summary>
        internal static string AddActionWithPartialView_PartialView {
            get {
                return ResourceManager.GetString("AddActionWithPartialView_PartialView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${Usings}
        ///
        ///namespace ${Namespace.Area}.Controllers
        ///{
        ///	public partial class ${ControllerKey}Controller 
        ///	{
        ///		[AcceptVerbs(HttpVerbs.Get)]
        ///		public virtual ActionResult ${ControllerActionKey}()
        ///		{
        ///			ActionResult result = null;
        ///
        ///			var model = new ${Namespace.Area}.Models.${ControllerKey}.${ControllerActionKey}Model();
        ///
        ///			result = View(${Namespace}.T4Files.${Areas.AreaName}Views.${ControllerKey}.${ControllerActionKey}_cshtml, model);
        ///
        ///			return result;
        ///		}
        ///
        ///		[AcceptVerbs(HttpVerbs.Post),  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddActionWithView_Action {
            get {
                return ResourceManager.GetString("AddActionWithView_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jQuery.namespace(&quot;${Namespace.Area}.${ControllerKey}.${ControllerActionKey}&quot;, function(jQuery) {
        ///	var model = {};
        ///	var view = {};
        ///	var controller = {
        ///		setup: function (config) {
        ///			controller.eventBinder();
        ///		},
        ///		eventBinder: function () {
        ///		}
        ///	};
        ///
        ///	return {
        ///		Setup: controller.setup
        ///	};
        ///} (jQuery));
        ///
        ///jQuery(document).ready(function (jQuery) {
        ///	${Namespace.Area}.${ControllerKey}.${ControllerActionKey}.Setup();
        ///});.
        /// </summary>
        internal static string AddActionWithView_JavaScript {
            get {
                return ResourceManager.GetString("AddActionWithView_JavaScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Web;
        ///
        ///namespace ${Namespace.Area}.Models.${ControllerKey}
        ///{
        ///	public class ${ControllerActionKey}Model : BaseModel
        ///	{
        ///
        ///	}
        ///}.
        /// </summary>
        internal static string AddActionWithView_Model {
            get {
                return ResourceManager.GetString("AddActionWithView_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Html.ImportStyleSheet(${Namespace}.T4Links.StyleSheets._Shared._Definitions_csless).
        /// </summary>
        internal static string AddActionWithView_StyleSheet {
            get {
                return ResourceManager.GetString("AddActionWithView_StyleSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model ${Namespace.Area}.Models.${ControllerKey}.${ControllerActionKey}Model
        ///
        ///@{
        ///	Model.SetTitle(&quot;${ViewTitle}&quot;);
        ///	Layout = ${Namespace}.T4Files.${Areas.AreaName}Views.${ControllerKey}._Layout_cshtml;
        ///}
        ///
        ///@section StyleSheetIncludes
        ///{
        ///	@Html.AddStyleSheet(${Namespace}.T4Links.${Areas.AreaName}StyleSheets.${ControllerKey}.${ControllerActionKey}_csless)
        ///}
        ///
        ///@section JavaScriptIncludes
        ///{
        ///	@Html.AddJavaScript(${Namespace}.T4Links.${Areas.AreaName}JavaScripts.${ControllerKey}.${ControllerActionKey}_c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddActionWithView_View {
            get {
                return ResourceManager.GetString("AddActionWithView_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Web;
        ///using System.Web.Mvc;
        ///using ISI.Libraries.Web.Mvc.Extensions;
        ///using ISI.Libraries.Extensions;
        ///
        ///namespace ${Namespace}.Areas.${AreaName}
        ///{
        ///	public class AreaRegistration : System.Web.Mvc.AreaRegistration
        ///	{
        ///		public override string AreaName { get { return GetType().Namespace; } }
        ///
        ///		public override void RegisterArea(System.Web.Mvc.AreaRegistrationContext contex [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddArea_AreaRegistration {
            get {
                return ResourceManager.GetString("AddArea_AreaRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Web;
        ///using System.Web.Mvc;
        ///using ISI.Libraries.Web.Mvc.Extensions;
        ///using ISI.Libraries.Extensions;
        ///
        ///namespace ${Namespace.Area}.Models
        ///{
        ///	public abstract class BaseModel : ${Namespace}.Models.BaseModel
        ///	{
        ///	}
        ///}.
        /// </summary>
        internal static string AddArea_BaseModel {
            get {
                return ResourceManager.GetString("AddArea_BaseModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Web;
        ///using System.Web.Mvc;
        ///using ISI.Libraries.Web.Mvc.Extensions;
        ///using ISI.Libraries.Extensions;
        ///
        ///namespace ${Namespace}.Areas.${AreaName}.Controllers
        ///{
        ///	public abstract partial class Controller : ${Namespace}.Controllers.Controller
        ///	{
        ///		protected Controller(ISI.Libraries.Tracing.ITrace trace)
        ///			: base(trace)
        ///		{
        ///
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string AddArea_Controller {
            get {
                return ResourceManager.GetString("AddArea_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Web;
        ///using System.Web.Mvc;
        ///using ISI.Libraries.Web.Mvc.Extensions;
        ///using ISI.Libraries.Extensions;
        ///
        ///namespace ${Namespace}.Areas.${AreaName}
        ///{
        ///	public partial class ModelBinders
        ///	{
        ///		public static void RegisterModelBinders(System.Web.Mvc.ModelBinderDictionary binders)
        ///		{
        ///			//${ModelBinders}
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string AddArea_ModelBinders {
            get {
                return ResourceManager.GetString("AddArea_ModelBinders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Web;
        ///using System.Web.Mvc;
        ///using ISI.Libraries.Web.Mvc.Extensions;
        ///using ISI.Libraries.Extensions;
        ///using System.Web.Routing;
        ///using ISI.Libraries.Web.Routes;
        ///
        ///namespace ${Namespace}.Areas.${AreaName}
        ///{
        ///	public partial class Routes
        ///	{
        ///		internal static readonly string UrlRoot = ${Namespace}.Routes.UrlRoot + &quot;${BaseUrl}/&quot;;
        ///
        ///		public static void RegisterRoutes(RouteC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddArea_Routes {
            get {
                return ResourceManager.GetString("AddArea_Routes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${Usings}
        ///
        ///namespace ${Namespace.Area}.Controllers
        ///{
        ///	public partial class ${ControllerKey}Controller 
        ///	{
        ///		[AcceptVerbs(HttpVerbs.Post)]
        ///		public virtual async Taskk&lt;ActionResult&gt; ${ControllerActionKey}Async()
        ///		{
        ///			ActionResult result = null;
        ///
        ///			var model = new ${Namespace.Area}.Models.${ControllerKey}.${ControllerActionKey}Model();
        ///
        ///			result = PartialView(${Namespace}.T4Files.${Areas.AreaName}Views.${ControllerKey}.Partials.${ControllerActionKey}_cshtml, model);
        ///
        ///			return result;
        ///		}        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddAsyncActionWithPartialView_Action {
            get {
                return ResourceManager.GetString("AddAsyncActionWithPartialView_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${Usings}
        ///
        ///namespace ${Namespace.Area}.Controllers
        ///{
        ///	public partial class ${ControllerKey}Controller 
        ///	{
        ///		[AcceptVerbs(HttpVerbs.Get)]
        ///		public async virtual Task&lt;ActionResult&gt; ${ControllerActionKey}Async()
        ///		{
        ///			ActionResult result = null;
        ///
        ///			var model = new ${Namespace.Area}.Models.${ControllerKey}.${ControllerActionKey}Model();
        ///
        ///			result = View(${Namespace}.T4Files.${Areas.AreaName}Views.${ControllerKey}.${ControllerActionKey}_cshtml, model);
        ///
        ///			return result;
        ///		}
        ///
        ///		[AcceptVerbs( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddAsyncActionWithView_Action {
            get {
                return ResourceManager.GetString("AddAsyncActionWithView_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${Usings}
        ///
        ///namespace ${Namespace.Area}.Controllers
        ///{
        ///	public partial class ${ControllerKey}Controller 
        ///	{
        ///		[AcceptVerbs(HttpVerbs.Post)]
        ///		public async virtual Task&lt;ActionResult&gt; ${ControllerActionKey}Async()
        ///		{
        ///			ActionResult result = null;
        ///
        ///			var model = new ${Namespace.Area}.Models.${ControllerKey}.${ControllerActionKey}Model();
        ///
        ///			return result;
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string AddAsyncRestMethod_Action {
            get {
                return ResourceManager.GetString("AddAsyncRestMethod_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Web;
        ///using System.Web.Mvc;
        ///using ISI.Libraries.Web.Mvc.Extensions;
        ///using ISI.Libraries.Extensions;
        ///
        ///namespace ${Namespace.Area}.Models.${ControllerKey}
        ///{
        ///	public abstract class BaseModel : Models.BaseModel
        ///	{
        ///	}
        ///}.
        /// </summary>
        internal static string AddController_BaseModel {
            get {
                return ResourceManager.GetString("AddController_BaseModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Web;
        ///using System.Web.Mvc;
        ///using ISI.Libraries.Web.Mvc.Extensions;
        ///using ISI.Libraries.Extensions;
        ///
        ///namespace ${Namespace}.Models
        ///{
        ///	public abstract class BaseModel
        ///	{
        ///
        ///	}
        ///}.
        /// </summary>
        internal static string AddController_BaseModelRoot {
            get {
                return ResourceManager.GetString("AddController_BaseModelRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Web;
        ///using System.Web.Mvc;
        ///using ISI.Libraries.Web.Mvc.Extensions;
        ///using ISI.Libraries.Extensions;
        ///
        ///namespace ${Namespace.Area}.Controllers
        ///{
        ///	public partial class ${ControllerKey}Controller : Controller
        ///	{
        ///		public ${ControllerKey}Controller(ISI.Libraries.Tracing.ITrace trace)
        ///			: base(trace)
        ///		{
        ///
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string AddController_Controller {
            get {
                return ResourceManager.GetString("AddController_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Web;
        ///using System.Web.Mvc;
        ///using ISI.Libraries.Web.Mvc.Extensions;
        ///using ISI.Libraries.Extensions;
        ///
        ///namespace ${Namespace.Area}.Controllers
        ///{
        ///	[SessionState(System.Web.SessionState.SessionStateBehavior.Disabled)]
        ///	public abstract partial class Controller : ISI.Libraries.Web.Mvc.AbstractController
        ///	{
        ///		protected Controller(ISI.Libraries.Tracing.ITrace trace)
        ///			: ba [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddController_ControllerRoot {
            get {
                return ResourceManager.GetString("AddController_ControllerRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Web;
        ///using System.Web.Mvc;
        ///using ISI.Libraries.Web.Mvc.Extensions;
        ///using ISI.Libraries.Extensions;
        ///
        ///namespace ${Namespace.Area}
        ///{
        ///	public partial class ModelBinders
        ///	{
        ///		public partial class ${ControllerKey}
        ///		{
        ///			public static void RegisterModelBinders(System.Web.Mvc.ModelBinderDictionary binders)
        ///			{
        ///				//binders.Add(typeof(Models.XXXXX.Entities.YYYYY), Syst [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddController_ModelBinders {
            get {
                return ResourceManager.GetString("AddController_ModelBinders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Web;
        ///using System.Web.Mvc;
        ///using ISI.Libraries.Web.Mvc.Extensions;
        ///using ISI.Libraries.Extensions;
        ///
        ///namespace ${Namespace.Area}
        ///{
        ///	public partial class ModelBinders
        ///	{
        ///		public static void RegisterModelBinders(System.Web.Mvc.ModelBinderDictionary binders)
        ///		{
        ///			System.Web.Mvc.ModelBinders.Binders.DefaultBinder = new ISI.Libraries.Web.Mvc.ModelBinders.ModelBinder() [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddController_ModelBindersRoot {
            get {
                return ResourceManager.GetString("AddController_ModelBindersRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Web;
        ///using System.Web.Mvc;
        ///using ISI.Libraries.Web.Mvc.Extensions;
        ///using ISI.Libraries.Extensions;
        ///using System.Web.Routing;
        ///using ISI.Libraries.Web.Routes;
        ///
        ///namespace ${Namespace.Area}
        ///{
        ///	public partial class Routes
        ///	{
        ///		public partial class ${ControllerKey}
        ///		{
        ///			#pragma warning disable 649
        ///			public class RouteNames : IRouteNames
        ///			{
        ///				//${RouteNames}
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddController_Routes {
            get {
                return ResourceManager.GetString("AddController_Routes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Web;
        ///using System.Web.Mvc;
        ///using ISI.Libraries.Web.Mvc.Extensions;
        ///using ISI.Libraries.Extensions;
        ///using System.Web.Routing;
        ///using ISI.Libraries.Web.Routes;
        ///
        ///namespace ${Namespace.Area}
        ///{
        ///	public partial class Routes
        ///	{
        ///		internal static readonly string UrlRoot = string.Empty;
        ///
        ///		public static void RegisterRoutes(RouteCollection routes)
        ///		{
        ///			routes.IgnoreRout [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddController_RoutesRoot {
            get {
                return ResourceManager.GetString("AddController_RoutesRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${Usings}
        ///
        ///namespace ${Namespace.Area}.Controllers
        ///{
        ///	public partial class ${ControllerKey}Controller 
        ///	{
        ///		[AcceptVerbs(HttpVerbs.Post)]
        ///		public virtual ActionResult ${ControllerActionKey}()
        ///		{
        ///			ActionResult result = null;
        ///
        ///			var model = new ${Namespace.Area}.Models.${ControllerKey}.${ControllerActionKey}Model();
        ///
        ///			return result;
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string AddRestMethod_Action {
            get {
                return ResourceManager.GetString("AddRestMethod_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Web;
        ///using System.Web.Mvc;
        ///using ISI.Libraries.Web.Mvc.Extensions;
        ///using ISI.Libraries.Extensions;
        ///
        ///namespace ${Namespace.Area}.Models.${ControllerKey}
        ///{
        ///	public class ${ControllerActionKey}Model : BaseModel
        ///	{
        ///
        ///	}
        ///}.
        /// </summary>
        internal static string AddRestMethod_Model {
            get {
                return ResourceManager.GetString("AddRestMethod_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Web;
        ///using System.Web.Mvc;
        ///using ISI.Libraries.Web.Mvc.Extensions;
        ///using ISI.Libraries.Extensions;
        ///using System.ServiceModel;
        ///
        ///namespace ${Namespace.Area}.Controllers
        ///{
        ///	[ServiceContract(Name = &quot;${ControllerKey}&quot;, Namespace = Namespaces.${ControllerKey}MethodsNamespace)]
        ///	[ServiceBehavior(Name = &quot;${ControllerKey}&quot;, AddressFilterMode = AddressFilterMode.Any)]
        ///	public [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddSoapController_Controller {
            get {
                return ResourceManager.GetString("AddSoapController_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jQuery.namespace(&quot;${Namespace.Area}.${ControllerKey}.Layout&quot;, function(jQuery) {
        ///	var model = {};
        ///	var view = {};
        ///	var controller = {
        ///		setup: function (config) {
        ///			controller.eventBinder();
        ///		},
        ///		eventBinder: function () {
        ///		}
        ///	};
        ///
        ///	return {
        ///		Setup: controller.setup
        ///	};
        ///} (jQuery));
        ///
        ///jQuery(document).ready(function (jQuery) {
        ///	${Namespace.Area}.${ControllerKey}.Layout.Setup();
        ///});.
        /// </summary>
        internal static string JavaScriptsControllerLayout {
            get {
                return ResourceManager.GetString("JavaScriptsControllerLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jQuery.namespace(&quot;${Namespace}.${Areas.AreaName}Layout&quot;, function(jQuery) {
        ///	var model = {};
        ///	var view = {};
        ///	var controller = {
        ///		setup: function (config) {
        ///			controller.eventBinder();
        ///		},
        ///		eventBinder: function () {
        ///		}
        ///	};
        ///
        ///	return {
        ///		Setup: controller.setup
        ///	};
        ///} (jQuery));
        ///
        ///jQuery(document).ready(function (jQuery) {
        ///	${Namespace}.${Areas.AreaName}Layout.Setup();
        ///});.
        /// </summary>
        internal static string JavaScriptsSharedLayout {
            get {
                return ResourceManager.GetString("JavaScriptsSharedLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;configuration&gt;
        ///	&lt;configSections&gt;
        ///		&lt;sectionGroup name=&quot;system.web.webPages.razor&quot; type=&quot;System.Web.WebPages.Razor.Configuration.RazorWebSectionGroup, System.Web.WebPages.Razor, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35&quot;&gt;
        ///			&lt;section name=&quot;host&quot; type=&quot;System.Web.WebPages.Razor.Configuration.HostSection, System.Web.WebPages.Razor, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35&quot; requirePermission=&quot;false&quot; /&gt;
        ///			&lt;section name=&quot;pages&quot; type=&quot;Sy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JavaScriptsWebConfig {
            get {
                return ResourceManager.GetString("JavaScriptsWebConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Html.ImportStyleSheet(${Namespace}.T4Links.StyleSheets._Shared._Definitions_csless).
        /// </summary>
        internal static string StyleSheetsControllerLayout {
            get {
                return ResourceManager.GetString("StyleSheetsControllerLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Html.ImportStyleSheet(${Namespace}.T4Links.StyleSheets._Shared._Definitions_csless).
        /// </summary>
        internal static string StyleSheetsSharedLayout {
            get {
                return ResourceManager.GetString("StyleSheetsSharedLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;configuration&gt;
        ///	&lt;configSections&gt;
        ///		&lt;sectionGroup name=&quot;system.web.webPages.razor&quot; type=&quot;System.Web.WebPages.Razor.Configuration.RazorWebSectionGroup, System.Web.WebPages.Razor, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35&quot;&gt;
        ///			&lt;section name=&quot;host&quot; type=&quot;System.Web.WebPages.Razor.Configuration.HostSection, System.Web.WebPages.Razor, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35&quot; requirePermission=&quot;false&quot; /&gt;
        ///			&lt;section name=&quot;pages&quot; type=&quot;Sy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StyleSheetsWebConfig {
            get {
                return ResourceManager.GetString("StyleSheetsWebConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model ${Namespace.Area}.Models.${ControllerKey}.BaseModel
        ///
        ///@{
        ///	Layout = ${Namespace}.T4Files.${Areas.AreaName}Views._Shared._Layout_cshtml;
        ///}
        ///
        ///@section StyleSheetIncludes
        ///{
        ///	@Html.AddStyleSheet(${Namespace}.T4Links.${Areas.AreaName}StyleSheets.${ControllerKey}._Layout_csless)
        ///	@RenderSection(&quot;StyleSheetIncludes&quot;, false)
        ///}
        ///
        ///@RenderBody()
        ///
        ///@section JavaScriptIncludes
        ///{
        ///	@Html.AddJavaScript(${Namespace}.T4Links.${Areas.AreaName}JavaScripts.${ControllerKey}._Layout_csjs)
        ///	@RenderSection(&quot;JavaS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ViewsControllerLayout {
            get {
                return ResourceManager.GetString("ViewsControllerLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @model ${Namespace.Area}.Models.BaseModel
        ///
        ///@{
        ///	Layout = ${Namespace}.T4Files.Views._Shared._Layout_cshtml;
        ///}
        ///
        ///@section StyleSheetIncludes
        ///{
        ///	@Html.AddStyleSheet(${Namespace}.T4Links.${Areas.AreaName}StyleSheets._Shared._Layout_csless)
        ///	@RenderSection(&quot;StyleSheetIncludes&quot;, false)
        ///}
        ///
        ///@RenderBody()
        ///
        ///@section JavaScriptIncludes
        ///{
        ///	@Html.AddJavaScript(${Namespace}.T4Links.${Areas.AreaName}JavaScripts._Shared._Layout_csjs)
        ///	@RenderSection(&quot;JavaScriptIncludes&quot;, false)
        ///}
        ///
        ///@section JavaScriptCont [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ViewsSharedLayout {
            get {
                return ResourceManager.GetString("ViewsSharedLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;configuration&gt;
        ///	&lt;configSections&gt;
        ///		&lt;sectionGroup name=&quot;system.web.webPages.razor&quot; type=&quot;System.Web.WebPages.Razor.Configuration.RazorWebSectionGroup, System.Web.WebPages.Razor, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35&quot;&gt;
        ///			&lt;section name=&quot;host&quot; type=&quot;System.Web.WebPages.Razor.Configuration.HostSection, System.Web.WebPages.Razor, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35&quot; requirePermission=&quot;false&quot; /&gt;
        ///			&lt;section name=&quot;pages&quot; type=&quot;Sy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ViewsWebConfig {
            get {
                return ResourceManager.GetString("ViewsWebConfig", resourceCulture);
            }
        }
    }
}
