//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISI.VisualStudio.Extensions.RecipeExtensions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Project_Recipes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Project_Recipes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ISI.VisualStudio.Extensions.RecipeExtensions.Project_Recipes", typeof(Project_Recipes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace ${Namespace}
        ///{
        ///	public partial class ${ClassNamePrefix}Request
        ///	{
        ///
        ///		public System.Threading.CancellationToken CancellationToken { get; set; } = default;
        ///	}
        ///}.
        /// </summary>
        internal static string AddAsyncDataTransferObjectRequest {
            get {
                return ResourceManager.GetString("AddAsyncDataTransferObjectRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${Usings}
        ///
        ///namespace ${Namespace}
        ///{
        ///	public partial class ${ClassName}
        ///	{
        ///		public async Task&lt;DTOs.${MethodName}Response&gt; ${MethodName}Async(DTOs.${MethodName}Request request)
        ///		{
        ///			var response = new DTOs.${MethodName}Response();
        ///			
        ///			
        ///			return response;
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string AddAsyncPartialClassMethod {
            get {
                return ResourceManager.GetString("AddAsyncPartialClassMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace ${Namespace}
        ///{
        ///	public partial class ${ClassNamePrefix}Request
        ///	{
        ///	}
        ///}.
        /// </summary>
        internal static string AddDataTransferObjectRequest {
            get {
                return ResourceManager.GetString("AddDataTransferObjectRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace ${Namespace}
        ///{
        ///	public partial class ${ClassNamePrefix}Response
        ///	{
        ///	}
        ///}.
        /// </summary>
        internal static string AddDataTransferObjectResponse {
            get {
                return ResourceManager.GetString("AddDataTransferObjectResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace ${Namespace}
        ///{
        ///	[ISI.Libraries.DependencyRegister]
        ///	public class DependencyRegister : ISI.Libraries.IDependencyRegister
        ///	{
        ///		void ISI.Libraries.IDependencyRegister.Register(ISI.Libraries.IDependencyResolver dependencyResolver)
        ///		{
        ///			dependencyResolver.Register&lt;IXXXXXXXXXXXXXXXXXXXXXXXXXXXX, XXXXXXXXXXXXXXXXXXXXXXXXXXXX&gt;(ISI.Libraries.DependencyResolverLifetime.Singleto [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddDependencyRegisterClass {
            get {
                return ResourceManager.GetString("AddDependencyRegisterClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;#@ template debug=&quot;true&quot; hostSpecific=&quot;true&quot; #&gt;
        ///&lt;#@ output extension=&quot;.generated.cs&quot; #&gt;
        ///&lt;#@ template language=&quot;C#&quot; #&gt;
        ///&lt;#@ assembly name=&quot;System.Core&quot; #&gt;
        ///&lt;#@ Assembly Name=&quot;EnvDTE&quot; #&gt;
        ///&lt;#@ Assembly Name=&quot;System.Data&quot; #&gt;
        ///&lt;#@ import namespace=&quot;EnvDTE&quot; #&gt;
        ///&lt;#@ import namespace=&quot;System.Data&quot; #&gt;
        ///&lt;#@ import namespace=&quot;System.Data.SqlClient&quot; #&gt;
        ///&lt;#@ import namespace=&quot;System.IO&quot; #&gt;
        ///&lt;#@ import namespace=&quot;System.Text.RegularExpressions&quot; #&gt;
        ///&lt;#@ import namespace=&quot;System.Linq&quot; #&gt;
        ///&lt;#
        ///		string enumName = Path.Ge [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddEnumTextTemplate {
            get {
                return ResourceManager.GetString("AddEnumTextTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${Usings}
        ///
        ///namespace ${Namespace}
        ///{
        ///	public partial class ${ClassName} : I${ClassName}
        ///	{
        ///${ClassInjectorProperties}
        ///		public ${ClassName}(${ClassInjectors})
        ///		{
        ///${ClassInjectorAssignments}
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string AddPartialClass {
            get {
                return ResourceManager.GetString("AddPartialClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${Usings}
        ///
        ///namespace ${Namespace}
        ///{
        ///	public partial class ${ClassName}
        ///	{
        ///		public DTOs.${MethodName}Response ${MethodName}(DTOs.${MethodName}Request request)
        ///		{
        ///			var response = new DTOs.${MethodName}Response();
        ///			
        ///			
        ///			return response;
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string AddPartialClassMethod {
            get {
                return ResourceManager.GetString("AddPartialClassMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${Usings}
        ///
        ///namespace ${Namespace}
        ///{
        ///	public partial class ${ClassName}
        ///	{
        ///		public void ${MethodName}()
        ///		{
        ///
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string AddPartialClassPrivateMethod {
            get {
                return ResourceManager.GetString("AddPartialClassPrivateMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${Usings}
        ///
        ///namespace ${Namespace}
        ///{
        ///	public partial class ${ClassName}
        ///	{
        ///		public partial class ${SubClassName}
        ///		{
        ///
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string AddPartialClassSubClass {
            get {
                return ResourceManager.GetString("AddPartialClassSubClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace ${Namespace}
        ///{
        ///	[ISI.Libraries.StartUp]
        ///	public class StartUp : ISI.Libraries.IStartUp
        ///	{
        ///		private static bool _isInitialized = false;
        ///		public void Start()
        ///		{
        ///			if (!_isInitialized)
        ///			{
        ///				_isInitialized = true;
        ///
        ///				ISI.Libraries.VirtualFileRepositories.Register(typeof(StartUp));
        ///			}
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string AddStartUpClass {
            get {
                return ResourceManager.GetString("AddStartUpClass", resourceCulture);
            }
        }
    }
}
