//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISI.VisualStudio.Extensions.RecipeExtensions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProjectPartialClass_Recipes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectPartialClass_Recipes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ISI.VisualStudio.Extensions.RecipeExtensions.ProjectPartialClass_Recipes", typeof(ProjectPartialClass_Recipes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${Usings}
        ///
        ///namespace ${Namespace}
        ///{
        ///	public partial class ${ClassName}
        ///	{
        ///		public async Task&lt;DTOs.${MethodName}Response&gt; ${MethodName}Async(DTOs.${MethodName}Request request)
        ///		{
        ///			var response = new DTOs.${MethodName}Response();
        ///			
        ///			
        ///			return response;
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string AddAsyncPartialClassMethod {
            get {
                return ResourceManager.GetString("AddAsyncPartialClassMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${Usings}
        ///
        ///namespace ${Namespace}
        ///{
        ///	public partial class ${ClassName}
        ///	{
        ///		private async Task ${MethodName}()
        ///		{
        ///
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string AddAsyncPartialClassPrivateMethod {
            get {
                return ResourceManager.GetString("AddAsyncPartialClassPrivateMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${Usings}
        ///
        ///namespace ${Namespace}
        ///{
        ///	public partial class ${ClassName} : I${ClassName}
        ///	{
        ///${ClassInjectorProperties}
        ///		public ${ClassName}(${ClassInjectors})
        ///		{
        ///${ClassInjectorAssignments}
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string AddPartialClass {
            get {
                return ResourceManager.GetString("AddPartialClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${Usings}
        ///
        ///namespace ${Namespace}
        ///{
        ///	public partial class ${ClassName}
        ///	{
        ///		public DTOs.${MethodName}Response ${MethodName}(DTOs.${MethodName}Request request)
        ///		{
        ///			var response = new DTOs.${MethodName}Response();
        ///			
        ///			
        ///			return response;
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string AddPartialClassMethod {
            get {
                return ResourceManager.GetString("AddPartialClassMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${Usings}
        ///
        ///namespace ${Namespace}
        ///{
        ///	public partial class ${ClassName}
        ///	{
        ///		private void ${MethodName}()
        ///		{
        ///
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string AddPartialClassPrivateMethod {
            get {
                return ResourceManager.GetString("AddPartialClassPrivateMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${Usings}
        ///
        ///namespace ${Namespace}
        ///{
        ///	public partial class ${ClassName}
        ///	{
        ///		public partial class ${SubClassName}
        ///		{
        ///
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string AddPartialClassSubClass {
            get {
                return ResourceManager.GetString("AddPartialClassSubClass", resourceCulture);
            }
        }
    }
}
