// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ISI.VisualStudio.Extensions
{
    internal sealed partial class Vsix
    {
        public const string Id = "ISI.VisualStudio.Extensions.9ccf3f26-98d6-4e65-abc4-92c62db4a0df";
        public const string Name = "ISI.VisualStudio.Extensions";
        public const string Description = @"ISI.VisualStudio.Extensions";
        public const string Language = "en-US";
        public const string Version = "2022.9";
        public const string Author = "Integrated Solution Inc";
        public const string Tags = "Cake,Jenkins";
    }
}
