// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ISI.VisualStudio.Extensions
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string LanternIconUuidString = "a52a4dbc-6209-46ac-9c01-d9c1be7c7b3a";
        public static Guid LanternIconUuid = new Guid(LanternIconUuidString);

        public const string PackageUuidString = "a7a5b1a5-2b35-4eab-af56-8d3beda18c7a";
        public static Guid PackageUuid = new Guid(PackageUuidString);

        public const string PackagePasteAsXmlCommandSetUuidString = "ead526ca-8a42-440d-968b-39444312d652";
        public static Guid PackagePasteAsXmlCommandSetUuid = new Guid(PackagePasteAsXmlCommandSetUuidString);

        public const string PackagePasteAsJsonCommandSetUuidString = "822a7feb-3d9d-4161-bf13-92834f141157";
        public static Guid PackagePasteAsJsonCommandSetUuid = new Guid(PackagePasteAsJsonCommandSetUuidString);

        public const string PackageTextEditorCommandSetUuidString = "8b382828-6202-11d1-8870-0000f87579d2";
        public static Guid PackageTextEditorCommandSetUuid = new Guid(PackageTextEditorCommandSetUuidString);

        public const string PackageHtmlCommandSetUuidString = "78f03954-2fb8-4087-8ce7-59d71710b3bb";
        public static Guid PackageHtmlCommandSetUuid = new Guid(PackageHtmlCommandSetUuidString);

        public const string PackageCssCommandSetUuidString = "64da400e-b4ad-4d67-aa92-4b7acb01ecd5";
        public static Guid PackageCssCommandSetUuid = new Guid(PackageCssCommandSetUuidString);

        public const string PackageJsonCommandSetUuidString = "f718ca06-cf4f-4a0c-9106-e79e9ee5e7cd";
        public static Guid PackageJsonCommandSetUuid = new Guid(PackageJsonCommandSetUuidString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int LanternIcon = 0x0001;
        public const int AboutMenuGroupId = 0x1020;
        public const int ToolsMenuGroupId = 0x1021;
        public const int SolutionMenuGroupId = 0x1022;
        public const int ProjectMenuGroupId = 0x1023;
        public const int FolderMenuGroupId = 0x1024;
        public const int ItemMenuGroupId = 0x1025;
        public const int EditorContextMenuGroupId = 0x1026;
        public const int ProjectReferencesMenuGroupId = 0x1027;
        public const int ProjectReferenceMenuGroupId = 0x1028;
        public const int AboutMenuItemId = 0x0105;
        public const int XmlConfigurationExtensions_AddTransform_MenuItemId = 0x0300;
        public const int XmlConfigurationExtensions_ExecuteTransform_MenuSubgroupId = 0x0301;
        public const int XmlConfigurationExtensions_ExecuteTransform_SubMenuId = 0x0302;
        public const int XmlConfigurationExtensions_Execute_MenuItemId = 0x0303;
        public const int AppSettingsExtensions_AddTransform_MenuItemId = 0x0330;
        public const int RecipeExtensions_AspNetMvc_5x_MenuSubgroupId = 0x0410;
        public const int RecipeExtensions_AspNetMvc_5x_SubMenuId = 0x0411;
        public const int RecipeExtensions_AspNetMvc_5x_CreateTemplates_MenuItemId = 0x0412;
        public const int RecipeExtensions_AspNetMvc_5x_AddArea_MenuItemId = 0x0413;
        public const int RecipeExtensions_AspNetMvc_5x_AddController_MenuItemId = 0x0414;
        public const int RecipeExtensions_AspNetMvc_5x_AddActionWithView_MenuItemId = 0x0416;
        public const int RecipeExtensions_AspNetMvc_5x_AddActionWithPartialView_MenuItemId = 0x0417;
        public const int RecipeExtensions_AspNetMvc_5x_AddRestMethod_MenuItemId = 0x0418;
        public const int RecipeExtensions_AspNetMvc_6x_MenuSubgroupId = 0x0420;
        public const int RecipeExtensions_AspNetMvc_6x_SubMenuId = 0x0421;
        public const int RecipeExtensions_AspNetMvc_6x_CreateTemplates_MenuItemId = 0x0422;
        public const int RecipeExtensions_AspNetMvc_6x_AddArea_MenuItemId = 0x0423;
        public const int RecipeExtensions_AspNetMvc_6x_AddController_MenuItemId = 0x0424;
        public const int RecipeExtensions_AspNetMvc_6x_AddActionWithView_MenuItemId = 0x0426;
        public const int RecipeExtensions_AspNetMvc_6x_AddActionWithPartialView_MenuItemId = 0x0427;
        public const int RecipeExtensions_AspNetMvc_6x_AddRestMethod_MenuItemId = 0x0428;
        public const int RecipeExtensions_AspNetWebApi_5x_MenuSubgroupId = 0x0430;
        public const int RecipeExtensions_AspNetWebApi_5x_SubMenuId = 0x0431;
        public const int RecipeExtensions_AspNetWebApi_5x_CreateTemplates_MenuItemId = 0x0432;
        public const int RecipeExtensions_AspNetWebApi_5x_AddArea_MenuItemId = 0x0433;
        public const int RecipeExtensions_AspNetWebApi_5x_AddController_MenuItemId = 0x0434;
        public const int RecipeExtensions_AspNetWebApi_5x_AddActionWithView_MenuItemId = 0x0435;
        public const int RecipeExtensions_AspNetWebApi_5x_AddActionWithPartialView_MenuItemId = 0x0436;
        public const int RecipeExtensions_AspNetWebApi_5x_AddRestMethod_MenuItemId = 0x0437;
        public const int RecipeExtensions_MessageBus_MenuSubgroupId = 0x0440;
        public const int RecipeExtensions_MessageBus_SubMenuId = 0x0441;
        public const int RecipeExtensions_MessageBus_AddController_MenuItemId = 0x0442;
        public const int RecipeExtensions_MessageBus_AddMethod_MenuItemId = 0x0443;
        public const int RecipeExtensions_ProjectPartialClass_MenuSubgroupId = 0x04A0;
        public const int RecipeExtensions_Project_SubMenuId = 0x04A1;
        public const int RecipeExtensions_ProjectPartialClass_AddPartialClass_MenuItemId = 0x04A2;
        public const int RecipeExtensions_ProjectPartialClass_AddPartialClassMethod_MenuItemId = 0x04A3;
        public const int RecipeExtensions_ProjectPartialClass_AddPartialClassPrivateMethod_MenuItemId = 0x04A4;
        public const int RecipeExtensions_ProjectPartialClass_AddPartialClassSubClass_MenuItemId = 0x04A5;
        public const int RecipeExtensions_ProjectPartialClass_SyncPartialClassUsingStatements_MenuItemId = 0x04A6;
        public const int RecipeExtensions_ProjectPartialClass_AddDataTransferObjectRequestResponse_MenuItemId = 0x04AA;
        public const int RecipeExtensions_Project_AddSerializableDataTransferObjectRequestResponse_MenuItemId = 0x04AB;
        public const int RecipeExtensions_Project_AddSerializableObject_MenuItemId = 0x04AC;
        public const int RecipeExtensions_Project_AddSerializableRecord_MenuItemId = 0x04AD;
        public const int RecipeExtensions_Project_AddEnumTextTemplate_MenuItemId = 0x04B1;
        public const int RecipeExtensions_Project_AddStartUpClass_MenuItemId = 0x04C0;
        public const int RecipeExtensions_Project_AddDependencyRegisterClass_MenuItemId = 0x04C1;
        public const int RecipeExtensions_Project_AddServiceRegistrarClass_MenuItemId = 0x04C2;
        public const int RecipeExtensions_Project_AddT4LocalContent_MenuItemId = 0x04C3;
        public const int RecipeExtensions_Project_ProjectProperties_MenuItemId = 0x04C4;
        public const int RecipeExtensions_Project_AddRecordManager_MenuItemId = 0x04C5;
        public const int CakeExtensions_ExecuteDefaultTarget_MenuItemId = 0x0520;
        public const int CakeExtensions_ExecuteTarget_MenuSubgroupId = 0x0521;
        public const int CakeExtensions_ExecuteTarget_SubMenuId = 0x0522;
        public const int CakeExtensions_ExecuteTarget_MenuItemId = 0x0523;
        public const int JenkinsExtensions_PushJenkinsConfigToJenkins_MenuItemId = 0x05A0;
        public const int JenkinsExtensions_PullJenkinsConfigFromJenkins_MenuItemId = 0x05A1;
        public const int ClipboardExtensions_PasteAs_MenuItemId = 0x0700;
        public const int ClipboardExtensions_PasteAsCmdAppend_MenuItemId = 0x0703;
        public const int ClipboardExtensions_PasteAsConversion_MenuItemId = 0x0750;
        public const int ClipboardExtensions_Context_MenuSubgroupId = 0x0770;
        public const int ClipboardExtensions_Context_SubMenuId = 0x0771;
        public const int GuidExtensions_InsertNewGuid_MenuItemId = 0x0801;
        public const int SolutionExtensions_AddExistingProjects_MenuItemId = 0x0901;
        public const int SolutionExtensions_ShowSccInformation_MenuItemId = 0x0910;
        public const int SolutionExtensions_UseLocalSourcePackages_MenuItemId = 0x0920;
        public const int SolutionExtensions_AddMissingLocalSourcePackages_MenuItemId = 0x0921;
        public const int ProjectExtensions_ProjectAddEmbeddedResources_MenuItemId = 0x0B01;
        public const int ProjectExtensions_ProjectUnloadProject_MenuItemId = 0x0B02;
        public const int ProjectExtensions_ProjectLoadProject_MenuItemId = 0x0B03;
        public const int ReferenceExtensions_CopyReferencesAsProjectReferences_MenuItemId = 0x0C80;
        public const int ReferenceExtensions_PasteAsProjectReferences_MenuItemId = 0x0C81;
        public const int NugetExtensions_CopyReferencesAsNugetPackages_MenuItemId = 0x0C00;
        public const int NugetExtensions_PasteAsNugetPackages_MenuItemId = 0x0C01;
        public const int PasteAsXmlMenuItemId = 0x0300;
        public const int PasteAsJsonMenuItemId = 0x0100;
        public const int HtmlClipboardSubMenuId = 0x0064;
        public const int CssClipboardSubMenuId = 0x0064;
        public const int JsonClipboardSubMenuId = 0x0064;
    }
}