// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ISI.VisualStudio.Extensions
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string PackageTextEditorCommandSetUuidString = "8b382828-6202-11d1-8870-0000f87579d2";
        public static Guid PackageTextEditorCommandSetUuid = new Guid(PackageTextEditorCommandSetUuidString);

        public const string PackageUuidString = "a7a5b1a5-2b35-4eab-af56-8d3beda18c7a";
        public static Guid PackageUuid = new Guid(PackageUuidString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int GuidExtensionsInsertNewGuidMenuItemId = 0x0801;
    }
}