//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by ISI.Extensions.VisualStudio.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyVersion("2025.12.*")]
